name: Lint

on: [pull_request, push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: install dependencies
        run: yarn install
      - name: Lint
        run: yarn lint && yarn workspace @force-bridge/ui run lint
